service: shop-lambda
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2

functions:
  api:
    handler: index.handler
    events:
      - httpApi: "*"
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sns:Publish
        Resource: "arn:aws:sns:ap-northeast-2:807207935784:order-topic"
